Refactor code structure for improved readability and maintainability

diff --git a/docker/Dockerfile b/docker/Dockerfile
--- a/docker/Dockerfile
+++ b/docker/Dockerfile
@@ -11,10 +11,13 @@ SHELL ["/bin/bash", "-c"]
 # Install basic apt packages
 RUN apt-get update && apt-get install -y --no-install-recommends \
  curl git libcanberra-gtk-module libcanberra-gtk3-module fuse3 libfuse2 libqt5svg5-dev \
- python3-pip python3-opencv python3-tk python3-pyqt5.qtwebengine
+ python3-pip python3-opencv python3-tk python3-pyqt5.qtwebengine 
+ 
+ # Foxglove Bridge 
+ RUN apt-get update && apt-get install -y --no-install-recommends ros-${ROS_DISTRO}-foxglove-bridge
 
 # Install additional Python modules
-RUN pip3 install --break-system-packages matplotlib transforms3d
+RUN pip3 install --break-system-packages matplotlib transforms3d pyrobosim rvc3python
 
 # Use Cyclone DDS as middleware
 RUN apt-get update && apt-get install -y --no-install-recommends \
@@ -32,8 +35,16 @@ WORKDIR /turtlebot_ws
 RUN source /opt/ros/${ROS_DISTRO}/setup.bash \
  && apt-get update -y \
  && rosdep install --from-paths src --ignore-src --rosdistro ${ROS_DISTRO} -y \
- && colcon build --symlink-install
-ENV TURTLEBOT_MODEL=3
+ && colcon build --symlink-install \
+ && echo "Built packages:" \
+ && source install/setup.bash \
+ && ros2 pkg list
+    ENV TURTLEBOT_MODEL=3
+
+# Test specific package availability
+RUN source /turtlebot_ws/install/setup.bash \
+ && ros2 pkg list | grep foxglove && echo "Foxglove bridge installed!" \
+ || (echo "ERROR: Foxglove bridge not installed" && exit 1)
 
 # Download Groot2 AppImage and place it in the home folder.
 WORKDIR /root/
@@ -91,11 +102,16 @@ RUN touch /var/mail/ubuntu \
 
 # Create new user and home directory
 RUN groupadd --gid $GID $USERNAME \
- && useradd --uid ${GID} --gid ${UID} --create-home ${USERNAME} \
+ && useradd --uid ${UID} --gid ${GID} --create-home ${USERNAME} \
  && echo ${USERNAME} ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/${USERNAME} \
  && chmod 0440 /etc/sudoers.d/${USERNAME} \
  && mkdir -p /home/${USERNAME} \
  && chown -R ${UID}:${GID} /home/${USERNAME}
+
+# BEFORE switching to non-root user:
+RUN mkdir -p /tmp/runtime-root && \
+    chown -R ${UID}:${GID} /tmp/runtime-root && \
+    chmod -R 0700 /tmp/runtime-root
 
 # Set the ownership of the overlay workspace to the new user
 RUN chown -R ${UID}:${GID} /overlay_ws/
@@ -106,6 +122,12 @@ RUN groupadd fuse \
 RUN mv /root/Groot2.AppImage /home/${USERNAME} \ 
  && chown ${UID}:${GID} /home/${USERNAME}/Groot2.AppImage
 
+# Add devuser to video group for GPU access
+RUN usermod -aG video ${USERNAME}
+# Create render group if it doesn't exist and add user to it
+RUN groupadd -f render && usermod -aG render ${USERNAME}
+
 # Set up the entrypoint, including it in the .bashrc for interactive shells
 USER ${USERNAME}
+ENV XDG_RUNTIME_DIR="/tmp/runtime-root"
 RUN echo "source /entrypoint.sh" >> /home/${USERNAME}/.bashrc
